## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns = ['EIN', 'NAME', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT'], inplace = True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,1
...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,0

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
STATUS               2
INCOME_AMT           9
IS_SUCCESSFUL        2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_type_value= application_df['APPLICATION_TYPE'].value_counts()
application_type_value

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace= list(application_type_value[application_type_value<250].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_counts= application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts.loc[classification_counts >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace= list (classification_counts[classification_counts <550].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df= pd.get_dummies(application_df)
dummies_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,1,0,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,1,1,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [ ]:
# Split our preprocessed data into our features and target arrays
X =  dummies_df.drop(['IS_SUCCESSFUL'], 1).values
y = dummies_df['IS_SUCCESSFUL'].values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state= 1)

<ipython-input-10-cb6d36ed7c5d>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X =  dummies_df.drop(['IS_SUCCESSFUL'], 1).values

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

X_train_scaled.shape

(25724, 41)


## Compile, Train and Evaluate the Model

## Attempt 1
First attempt accuracy 73%

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 85
hidden_nodes_layer2 = 50

nn_op1 = tf.keras.models.Sequential()

# First hidden layer
nn_op1.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='relu', input_dim=41))

# Second hidden layer
nn_op1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='tanh'))

# Output layer
nn_op1.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

# Check the structure of the model
nn_op1.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_70 (Dense)            (None, 85)                3570

 dense_71 (Dense)            (None, 50)                4300

 dense_72 (Dense)            (None, 1)                 51

=================================================================
Total params: 7921 (30.94 KB)
Trainable params: 7921 (30.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_op1.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [ ]:
# Train the model
fit_model = nn_op1.fit(X_train_scaled, y_train, epochs=9)

Epoch 1/9
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7337
Epoch 2/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7347
Epoch 3/9
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 4/9
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7338
Epoch 5/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7332
Epoch 6/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7344
Epoch 7/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7360
Epoch 8/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7359
Epoch 9/9
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7355

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_op1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5518 - accuracy: 0.7300 - 331ms/epoch - 1ms/step
Loss: 0.5517563223838806, Accuracy: 0.7300291657447815

In [ ]:
# Export our model to HDF5 file
nn_op1.save('/content/drive/My Drive/deep-learning-challenge/AlphabetSoupCharity_Optimization_1.h5')

## Attempt 2
2nd Attempt - Accurate 73%

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =120
hidden_nodes_layer2 = 45
hidden_nodes_layer3 = 12

nn_op2 = tf.keras.models.Sequential()

# First hidden layer
nn_op2.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='tanh', input_dim=41))

# Second hidden layer
nn_op2.add(tf.keras.layers.Dense(units= hidden_nodes_layer2, activation='tanh'))

# Third hidden layer
nn_op2.add(tf.keras.layers.Dense(units= hidden_nodes_layer3, activation= 'relu'))

# Output layer
nn_op2.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

# Check the structure of the model
nn_op2.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_63 (Dense)            (None, 120)               5040

 dense_64 (Dense)            (None, 45)                5445

 dense_65 (Dense)            (None, 12)                552

 dense_66 (Dense)            (None, 1)                 13

=================================================================
Total params: 11050 (43.16 KB)
Trainable params: 11050 (43.16 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_op2.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [ ]:
# Train the model
fit_model = nn_op2.fit(X_train_scaled, y_train, epochs=4)

Epoch 1/4
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7363
Epoch 2/4
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 3/4
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7364
Epoch 4/4
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7361

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_op2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5512 - accuracy: 0.7307 - 497ms/epoch - 2ms/step
Loss: 0.5511821508407593, Accuracy: 0.7307288646697998

In [ ]:
# Export our model to HDF5 file
nn_op2.save('/content/drive/My Drive/deep-learning-challenge/AlphabetSoupCharity_Optimization_2.h5')

## Attempt 3

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 115
hidden_nodes_layer2 = 50
hidden_nodes_layer3 = 25
hidden_nodes_layer4 = 12

nn_op3 = tf.keras.models.Sequential()

# First hidden layer
nn_op3.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='tanh', input_dim=41))

# Second hidden layer
nn_op3.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='tanh'))

# Third hidden layer
nn_op3.add(tf.keras.layers.Dense(units= hidden_nodes_layer3, activation='tanh'))

# Fourth hidden layer
nn_op3.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation='tanh'))

# Output layer
nn_op3.add(tf.keras.layers.Dense(units=1, activation= 'sigmoid'))

# Check the structure of the model
nn_op3.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_58 (Dense)            (None, 115)               4830

 dense_59 (Dense)            (None, 50)                5800

 dense_60 (Dense)            (None, 25)                1275

 dense_61 (Dense)            (None, 12)                312

 dense_62 (Dense)            (None, 1)                 13

=================================================================
Total params: 12230 (47.77 KB)
Trainable params: 12230 (47.77 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_op3.compile(loss="binary_crossentropy", optimizer="adam", metrics= ["accuracy"])

In [ ]:
# Train the model
fit_model = nn_op3.fit(X_train_scaled, y_train, epochs=6)

Epoch 1/6
804/804 [==============================] - 3s 3ms/step - loss: 0.5666 - accuracy: 0.7239
Epoch 2/6
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7296
Epoch 3/6
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7314
Epoch 4/6
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 5/6
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7325
Epoch 6/6
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7332

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_op3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5525 - accuracy: 0.7312 - 491ms/epoch - 2ms/step
Loss: 0.5525369644165039, Accuracy: 0.731195330619812

In [ ]:
# Export our model to HDF5 file
nn_op3.save('/content/drive/My Drive/deep-learning-challenge/AlphabetSoupCharity_Optimization_3.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).